site_name: OncoMark
repo_url: https://github.com/SML-CompBio/OncoMark
site_author: 'Shreyansh Priyadarshi'
docs_dir: 'docs'
theme: readthedocs
nav:
  - Home: index.md
  - Workflow: dataset.md
  - Installation: installation.md
  - Usage: usage.md
  - Single-Cell Support: Single-Cell Support.md
